# Generated by Django 4.1.7 on 2024-10-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_alter_recommendation_model_search_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='softskill',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tecskill',
        ),
    ]
