# Generated by Django 4.1.7 on 2024-10-28 21:30

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_alter_profile_city_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.FileField(default='none', max_length=40, upload_to=profiles.models.user_directory_path),
        ),
    ]
